/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package it.ldc.libridicarta;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.PrintWriter;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.ZoneId;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.SwingWorker;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.filechooser.FileSystemView;
import org.apache.poi.ss.usermodel.DataFormatter;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.ss.usermodel.WorkbookFactory;
import org.apache.commons.io.FilenameUtils;

/**
 *
 * @author Federico
 */
public class Main extends javax.swing.JFrame {
    File workbook;
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        fileDestination.setText(FileSystemView.getFileSystemView().getDefaultDirectory().getPath() + "\\");
        
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        fileChooserButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        logArea = new javax.swing.JTextArea();
        startButton = new javax.swing.JButton();
        selectedFile = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        fileDestination = new javax.swing.JTextField();
        fileDestinationButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        salePercentage = new javax.swing.JTextField();
        descriptionValue = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        categoryValue = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        variazioneCombobox = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        worksheetTypeCombobox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        quantityTypeCombobox = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        dropdownImmagini = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WooCommerce CSV Creator");

        fileChooserButton.setText("Seleziona..");
        fileChooserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileChooserButtonActionPerformed(evt);
            }
        });

        logArea.setColumns(20);
        logArea.setRows(5);
        logArea.setFocusable(false);
        jScrollPane1.setViewportView(logArea);

        startButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        startButton.setText("START");
        startButton.setVisible(false);
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        selectedFile.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("File Excel di Mr Book:");

        fileDestination.setEnabled(false);

        fileDestinationButton.setText("Seleziona..");
        fileDestinationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileDestinationButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Cartella di destinazione (Crea un file CSV nella cartella):");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Seleziona lo sconto (es 40 per il 40%):");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Inserisci la descrizione (es Presenta penna):");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Inserisci la categoria:");

        variazioneCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nuovo", "Usato" }));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Condizione:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Seleziona il tipo di file:");

        worksheetTypeCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ordini", "Inventario" }));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Seleziona il tipo di quantita:");

        quantityTypeCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+", "-", "Esatta" }));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Includi immagini: ");

        dropdownImmagini.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(startButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(selectedFile)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fileChooserButton))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(0, 20, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                        .addComponent(fileDestination)
                                        .addGap(6, 6, 6)))
                                .addComponent(fileDestinationButton)))
                        .addGap(31, 31, 31))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(categoryValue, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(worksheetTypeCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(mainPanelLayout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(salePercentage, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel7))
                                        .addComponent(descriptionValue))
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(quantityTypeCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel9)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dropdownImmagini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(variazioneCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fileChooserButton)
                    .addComponent(selectedFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(worksheetTypeCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(5, 5, 5)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fileDestination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fileDestinationButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(salePercentage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(variazioneCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(quantityTypeCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(dropdownImmagini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descriptionValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(categoryValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fileChooserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileChooserButtonActionPerformed
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
                "Excel Files", "xls", "xlsx");
        chooser.setFileFilter(filter);
        int returnVal = chooser.showOpenDialog(null);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            selectedFile.setText(chooser.getSelectedFile().getName());
            workbook = chooser.getSelectedFile();
            startButton.setVisible(true);
        }
    }//GEN-LAST:event_fileChooserButtonActionPerformed

    private void fileDestinationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileDestinationButtonActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setAcceptAllFileFilterUsed(false);
        
        int returnVal = chooser.showOpenDialog(null);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            fileDestination.setText(chooser.getSelectedFile().getAbsolutePath() + "\\");
        }
    }//GEN-LAST:event_fileDestinationButtonActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        if(salePercentage != null && !salePercentage.getText().equals("")){
            startButton.setEnabled(false);
            logArea.setText(logArea.getText() + System.lineSeparator() + "Inizio creazione del file csv..");
            
            new csvVariationsCreator(workbook, variazioneCombobox.getSelectedIndex(), worksheetTypeCombobox.getSelectedIndex(), quantityTypeCombobox.getSelectedIndex(), this.logArea).execute();
            
        } else{
            JOptionPane.showMessageDialog(mainPanel, "Inserisci una percentuale di sconto!", "Errore", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_startButtonActionPerformed
    
    /*
    **
    **Kept for future reference (Might need it later)
    **This swingWorker creates a new csv Import file for simple products only
    **
    class csvCreator extends SwingWorker<Integer, Integer>{
        File f;
        JTextArea JTA;
        String initialJTAText;
        boolean errors;
        
        public csvCreator(File f, JTextArea JTA){
            this.f = f;
            this.JTA = JTA;
            this.initialJTAText = JTA.getText();
            this.errors = false;
        };

        @Override
        protected Integer doInBackground() throws Exception {
            try {
                //Creazione del workbook
                Workbook wb = WorkbookFactory.create(f);

                //Creazione del foglio di lavoro
                Sheet s = wb.getSheetAt(0);

                //Creazione della prima riga
                StringBuilder sb = new StringBuilder();
                sb.append("id");
                sb.append(',');
                sb.append("type");
                sb.append(',');
                sb.append("sku");
                sb.append(',');
                sb.append("name");
                sb.append(',');
                sb.append("pubblicato");
                sb.append(',');
                sb.append("catalog_visibility");
                sb.append(',');
                sb.append("short_description");
                sb.append(',');
                sb.append("description");
                sb.append(',');
                sb.append("tax_status");
                sb.append(',');
                sb.append("tax_class");
                sb.append(',');
                sb.append("stock_status");
                sb.append(',');
                sb.append("backorders");
                sb.append(',');
                sb.append("reviews_allowed");
                sb.append(',');
                sb.append("prezzo in offerta");
                sb.append(',');
                sb.append("prezzo di listino");
                sb.append(',');
                sb.append("magazzino");
                sb.append(',');
                sb.append("category_ids");
                sb.append('\n');

                int rows = s.getLastRowNum();
                
                String description = (descriptionValue.getText()!= null) ? descriptionValue.getText() : "";
                String category = (categoryValue.getText()!= null) ? categoryValue.getText() : "";
                BigDecimal percentageToRemove = new BigDecimal(salePercentage.getText());
                

                DataFormatter formatter = new DataFormatter();
                //Bisogna inserire solo valori dinamici dentro il csv
                for(int i = 0; i<rows+1; i++){
                    //System.out.println("Riga: "+ i + " - ISBN: " + formatter.formatCellValue(s.getRow(i).getCell(isbnIndex, Row.MissingCellPolicy.CREATE_NULL_AS_BLANK)));
                    //Controllo che sia una riga con un libro (Hanno la quantita)
                    if(!formatter.formatCellValue(s.getRow(i).getCell(quantityIndex, Row.MissingCellPolicy.CREATE_NULL_AS_BLANK)).equals("")){
                        int quantity= Integer.parseInt(formatter.formatCellValue(s.getRow(i).getCell(quantityIndex, Row.MissingCellPolicy.CREATE_NULL_AS_BLANK)));
                        while(formatter.formatCellValue(s.getRow(i).getCell(isbnIndex, Row.MissingCellPolicy.CREATE_NULL_AS_BLANK)).equals(formatter.formatCellValue(s.getRow(i+1).getCell(isbnIndex, Row.MissingCellPolicy.CREATE_NULL_AS_BLANK)))){
                            quantity += Integer.parseInt(formatter.formatCellValue(s.getRow(i).getCell(quantityIndex, Row.MissingCellPolicy.CREATE_NULL_AS_BLANK)));
                            i++;
                        }
                        //System.out.println("Quantita: " + quantity);
                        Row row = s.getRow(i);

                        //calcolo lo sconto (bisogna aggiungere il replaceAll perche' java tende a formattare i numeri in base al Locale di un computer e alcune lingue usano la , per separare i centesimi che BigDecimal non accetta
                        BigDecimal money = new BigDecimal(formatter.formatCellValue(row.getCell(moneyIndex, Row.MissingCellPolicy.CREATE_NULL_AS_BLANK)).replaceAll(",","."));
                        BigDecimal percentage = money.multiply(percentageToRemove);
                        percentage = percentage.divide(new BigDecimal("100"), RoundingMode.HALF_EVEN);
                        percentage = percentage.setScale(2, RoundingMode.HALF_EVEN);
                        money = money.subtract(percentage);


                        sb.append("");//id
                        sb.append(',');
                        sb.append("simple");//type
                        sb.append(',');
                        sb.append(formatter.formatCellValue(row.getCell(isbnIndex, Row.MissingCellPolicy.CREATE_NULL_AS_BLANK)));//sku
                        sb.append(',');
                        sb.append(formatter.formatCellValue(row.getCell(nameIndex, Row.MissingCellPolicy.CREATE_NULL_AS_BLANK)).replaceAll(",","."));//name
                        sb.append(',');
                        sb.append("1");//pubblicato
                        sb.append(',');
                        sb.append("visible");//catalog_visibility
                        sb.append(',');
                        sb.append("Autore: " + formatter.formatCellValue(row.getCell(authorIndex, Row.MissingCellPolicy.CREATE_NULL_AS_BLANK)) + "<br>Casa editrice: " + formatter.formatCellValue(row.getCell(publisherIndex, Row.MissingCellPolicy.CREATE_NULL_AS_BLANK)) + "<br>ISBN: " + formatter.formatCellValue(row.getCell(isbnIndex, Row.MissingCellPolicy.CREATE_NULL_AS_BLANK)));//short description
                        sb.append(',');
                        sb.append('"');
                        sb.append(description);//description
                        sb.append('"');
                        sb.append(',');
                        sb.append("taxable");//tax_status
                        sb.append(',');
                        sb.append("standard");//tax_class
                        sb.append(',');
                        sb.append("1");//stock_status
                        sb.append(',');
                        sb.append("0");//backorders
                        sb.append(',');
                        sb.append("1");//reviews_allowed
                        sb.append(',');
                        sb.append(money.toString());//prezzo_in_offerta
                        sb.append(',');
                        sb.append('"');
                        sb.append(formatter.formatCellValue(row.getCell(moneyIndex, Row.MissingCellPolicy.CREATE_NULL_AS_BLANK)));//Prezzo_di_listino
                        sb.append('"');
                        sb.append(',');
                        sb.append("+"+Integer.toString(quantity));//manage_stock/stock_quantitiy
                        sb.append(',');
                        sb.append('"');
                        sb.append(category);//category_ids
                        sb.append('"');
                        sb.append('\n');
                    }
                    int percentage = (100 * i)/rows;
                    publish(percentage);
                }
                Date date = new Date();
                LocalDate localDate = date.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
                PrintWriter out = new PrintWriter(new FileOutputStream(fileDestination.getText() + localDate.getDayOfMonth()+ "_" +localDate.getMonthValue()+ "_" + localDate.getYear()+ "_" + LocalTime.now().getHour() + LocalTime.now().getMinute() + LocalTime.now().getSecond() + "_" + FilenameUtils.removeExtension(f.getName())+ "_" +"WooCommerce_CSV_Import.csv"), true);
                out.println(sb.toString());

                //System.out.println(sb.toString());
                out.close();
                wb.close();
            } catch (Throwable ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(mainPanel, "Errore nella creazione del CSV", "Errore", JOptionPane.ERROR_MESSAGE);
                errors = true;
            }
            return null;
        }
        
        @Override
        protected void process(List<Integer> chunks) {
            //Aggiornamento della percentuale della progress bar
            int i = chunks.get(chunks.size()-1);
            JTA.setText(initialJTAText + System.lineSeparator() + "Progresso del file: " + i +"%");
        }
        
        @Override
        protected void done() {
            if(!errors){
                logArea.setText(JTA.getText() + System.lineSeparator() + "File CSV creato!");
            }else{
                logArea.setText(JTA.getText() + System.lineSeparator() + "Errore nella creazione del file CSV!");
            }
            startButton.setEnabled(true);
        }
    }
    */
    
    
    
    StringBuilder createLine(StringBuilder sb, String type, String sku, String name, String short_description, String description, String prezzo_in_offerta, String prezzo_di_listino, String quantity, String category, String parent_sku, String position, String attNome1, String attValuta1, String attPredef1, String fifuImgAlt, String fifuImgUrl, String galleryUrl){
        sb.append("");//id
        sb.append(',');
        sb.append(type);//type
        sb.append(',');
        sb.append(sku);//sku
        sb.append(',');
        sb.append(name);//name
        sb.append(',');
        sb.append("1");//pubblicato
        sb.append(',');
        sb.append("visible");//catalog_visibility
        sb.append(',');
        sb.append(short_description);//short description
        sb.append(',');
        sb.append('"');
        sb.append(description);//description
        sb.append('"');
        sb.append(',');
        sb.append("taxable");//tax_status
        sb.append(',');
        sb.append("standard");//tax_class
        sb.append(',');
        sb.append("1");//stock_status
        sb.append(',');
        sb.append("0");//backorders
        sb.append(',');
        sb.append("1");//reviews_allowed
        sb.append(',');
        sb.append('"');
        sb.append(prezzo_in_offerta);//prezzo_in_offerta
        sb.append('"');
        sb.append(',');
        sb.append('"');
        sb.append(prezzo_di_listino);//Prezzo_di_listino
        sb.append('"');
        sb.append(',');
        sb.append(quantity);//manage_stock/stock_quantitiy
        sb.append(',');
        sb.append('"');
        sb.append(category);//category_ids
        sb.append('"');
        sb.append(',');
        sb.append(parent_sku);//parent_sku
        sb.append(',');
        sb.append(position);//position
        sb.append(',');
        sb.append('"');
        sb.append(attNome1);//Attributo 1 nome
        sb.append('"');
        sb.append(',');
        sb.append('"');
        sb.append(attValuta1);//Attributo 1 valuta(e)
        sb.append('"');
        sb.append(',');
        sb.append(attPredef1);//Attributo 1 predefinito
        sb.append(',');
        sb.append('"');
        sb.append(fifuImgAlt);//FIFU img alt
        sb.append('"');
        sb.append(',');
        sb.append('"');
        sb.append(fifuImgUrl);//FIFU img url
        sb.append('"');
        sb.append(',');
        sb.append('"');
        sb.append(galleryUrl);//img gallery url
        sb.append('"');
        sb.append('\n');
        return sb;
    }
    
    class csvVariationsCreator extends SwingWorker<Integer, Integer>{
        File f;
        JTextArea JTA;
        String initialJTAText;
        int indice, worksheetType, quantityType;
        boolean errors;
        
        public csvVariationsCreator(File f, int indice, int worksheetType, int quantityType, JTextArea JTA){
            this.f = f;
            this.JTA = JTA;
            this.indice = indice;
            this.worksheetType = worksheetType;
            this.initialJTAText = JTA.getText();
            this.errors = false;
            this.quantityType = quantityType;
        };

        @Override
        protected Integer doInBackground() throws Exception {
            try {
                
                //Creazione del workbook
                Workbook wb = WorkbookFactory.create(f);

                //Creazione del foglio di lavoro
                Sheet s = wb.getSheetAt(0);
                
                
                //Creazione della prima riga
                StringBuilder sb = new StringBuilder();
                sb.append("id");
                sb.append(',');
                sb.append("type");
                sb.append(',');
                sb.append("sku");
                sb.append(',');
                sb.append("name");
                sb.append(',');
                sb.append("pubblicato");
                sb.append(',');
                sb.append("catalog_visibility");
                sb.append(',');
                sb.append("short_description");
                sb.append(',');
                sb.append("description");
                sb.append(',');
                sb.append("tax_status");
                sb.append(',');
                sb.append("tax_class");
                sb.append(',');
                sb.append("stock_status");
                sb.append(',');
                sb.append("backorders");
                sb.append(',');
                sb.append("reviews_allowed");
                sb.append(',');
                sb.append("prezzo in offerta");
                sb.append(',');
                sb.append("prezzo di listino");
                sb.append(',');
                sb.append("magazzino");
                sb.append(',');
                sb.append("category_ids");
                sb.append(',');
                sb.append("genitore");
                sb.append(',');
                sb.append("position");
                sb.append(',');
                sb.append("Attributo 1 nome");
                sb.append(',');
                sb.append("Attributo 1 valuta(e)");
                sb.append(',');
                sb.append("Attributo 1 predefinito");
                sb.append(',');
                sb.append("Meta: fifu_image_alt");
                sb.append(',');
                sb.append("Meta: fifu_image_url");
                sb.append(',');
                sb.append("Images");
                sb.append('\n');
                
                int rows = s.getLastRowNum();
                int quantity = 0;
                
                String description = (descriptionValue.getText()!= null) ? descriptionValue.getText() : "";
                String category = (categoryValue.getText()!= null) ? categoryValue.getText() : "";
                BigDecimal percentageToRemove = new BigDecimal(salePercentage.getText());
                
                DataFormatter formatter = new DataFormatter();
                
                int quantityIndex, isbnIndex, moneyIndex, nameIndex, authorIndex, publisherIndex = 0;
                String quantityTypeSelected = null;
                if(worksheetType == 0){//File Ordini
                    quantityIndex = 68;
                    isbnIndex = 62;
                    moneyIndex = 73;
                    nameIndex = 20;
                    authorIndex = 44;
                    publisherIndex = 52;
                }else{//File Inventario
                    quantityIndex = 23;
                    isbnIndex = 1;
                    moneyIndex = 18;
                    nameIndex = 4;
                    authorIndex = 5;
                    publisherIndex = 6;
                }
                switch (quantityType) {
                    case 0:
                        quantityTypeSelected = "+";
                        break;
                    case 1:
                        quantityTypeSelected = "-";
                        break;
                    default:
                        quantityTypeSelected = "";
                        break;
                }
                
                //Bisogna inserire solo libri nel csv
                for(int i = 0; i<rows+1; i++){
                    //System.out.println("Riga: "+ i + " - ISBN: " + formatter.formatCellValue(s.getRow(i).getCell(isbnIndex, Row.MissingCellPolicy.CREATE_NULL_AS_BLANK)));
                    //Controllo che sia una riga con un libro (Hanno la quantita)
                    if(!formatter.formatCellValue(s.getRow(i).getCell(quantityIndex, Row.MissingCellPolicy.CREATE_NULL_AS_BLANK)).equals("") && !formatter.formatCellValue(s.getRow(i).getCell(quantityIndex, Row.MissingCellPolicy.CREATE_NULL_AS_BLANK)).equals("dispusa")){
                        
                        quantity= Integer.parseInt(formatter.formatCellValue(s.getRow(i).getCell(quantityIndex, Row.MissingCellPolicy.CREATE_NULL_AS_BLANK)));
                        if(i<rows){
                            while(formatter.formatCellValue(s.getRow(i).getCell(isbnIndex, Row.MissingCellPolicy.CREATE_NULL_AS_BLANK)).equals(formatter.formatCellValue(s.getRow(i+1).getCell(isbnIndex, Row.MissingCellPolicy.CREATE_NULL_AS_BLANK)))){
                                quantity += Integer.parseInt(formatter.formatCellValue(s.getRow(i).getCell(quantityIndex, Row.MissingCellPolicy.CREATE_NULL_AS_BLANK)));
                                i++;
                            }
                        }
                        //System.out.println("Quantita: " + quantity);
                        Row row = s.getRow(i);

                        //calcolo lo sconto (bisogna aggiungere il replaceAll perche' java tende a formattare i numeri in base al Locale di un computer e alcune lingue usano la , per separare i centesimi che BigDecimal non accetta
                        BigDecimal money = new BigDecimal(formatter.formatCellValue(row.getCell(moneyIndex, Row.MissingCellPolicy.CREATE_NULL_AS_BLANK)).replaceAll(",","."));
                        BigDecimal percentage = money.multiply(percentageToRemove);
                        percentage = percentage.divide(new BigDecimal("100"), RoundingMode.HALF_EVEN);
                        percentage = percentage.setScale(2, RoundingMode.HALF_EVEN);
                        money = money.subtract(percentage);
                        
                        String image = ImmaginiEnum.SI.getIndex() == dropdownImmagini.getSelectedIndex() ? "https://www.libridicartaonline.it/isbnPictures/"+formatter.formatCellValue(row.getCell(isbnIndex, Row.MissingCellPolicy.CREATE_NULL_AS_BLANK))+".jpg" : "";
                         
                        String type = "variable";
                        //Il prodotto non e' stato trovato (non e' presente nell'export)

                        //creo la riga del genitore
                        createLine(
                        sb,
                        type,//type
                        formatter.formatCellValue(row.getCell(isbnIndex, Row.MissingCellPolicy.CREATE_NULL_AS_BLANK)),//sku
                        formatter.formatCellValue(row.getCell(nameIndex, Row.MissingCellPolicy.CREATE_NULL_AS_BLANK)).replaceAll(",","."),//name
                        "Autore: " + formatter.formatCellValue(row.getCell(authorIndex, Row.MissingCellPolicy.CREATE_NULL_AS_BLANK)) + "<br>Casa editrice: " + formatter.formatCellValue(row.getCell(publisherIndex, Row.MissingCellPolicy.CREATE_NULL_AS_BLANK)) + "<br>ISBN: " + formatter.formatCellValue(row.getCell(isbnIndex, Row.MissingCellPolicy.CREATE_NULL_AS_BLANK)),//short description
                        description,//description
                        "",//prezzo_in_offerta
                        "",//Prezzo_di_listino
                        "",//manage_stock/stock_quantitiy
                        category,//category_ids
                        "",//parent_sku
                        "0",//position
                        "condizione",//Attributo 1 nome
                        "Nuovo, Usato",//Attributo 1 valuta(e)
                        "Usato",//Attributo 1 predefinito
                        formatter.formatCellValue(row.getCell(nameIndex, Row.MissingCellPolicy.CREATE_NULL_AS_BLANK)).replaceAll(",","."),
                        image,
                        image
                        );

                        if(indice == 0){//Nuovo
                            createLine(
                            sb,
                            "variation",//type
                            formatter.formatCellValue(row.getCell(isbnIndex, Row.MissingCellPolicy.CREATE_NULL_AS_BLANK))+"-n",//sku
                            formatter.formatCellValue(row.getCell(nameIndex, Row.MissingCellPolicy.CREATE_NULL_AS_BLANK)).replaceAll(",",".") + " - Nuovo",//name
                            "",//short description
                            "",//description
                            money.toString(),//prezzo_in_offerta
                            formatter.formatCellValue(row.getCell(moneyIndex, Row.MissingCellPolicy.CREATE_NULL_AS_BLANK)),//Prezzo_di_listino
                            quantityTypeSelected+Integer.toString(quantity),//manage_stock/stock_quantitiy
                            "",//category_ids
                            formatter.formatCellValue(row.getCell(isbnIndex, Row.MissingCellPolicy.CREATE_NULL_AS_BLANK)),//parent_sku
                            "1",//position
                            "condizione",//Attributo 1 nome
                            "Nuovo",//Attributo 1 valuta(e)
                            "",//Attributo 1 predefinito
                            "",
                            "",
                            ""
                            );
                        } else {//Usato
                            createLine(
                            sb,
                            "variation",//type
                            formatter.formatCellValue(row.getCell(isbnIndex, Row.MissingCellPolicy.CREATE_NULL_AS_BLANK))+"-u",//sku
                            formatter.formatCellValue(row.getCell(nameIndex, Row.MissingCellPolicy.CREATE_NULL_AS_BLANK)).replaceAll(",",".") + " - Usato",//name
                            "",//short description
                            "",//description
                            money.toString(),//prezzo_in_offerta
                            formatter.formatCellValue(row.getCell(moneyIndex, Row.MissingCellPolicy.CREATE_NULL_AS_BLANK)),//Prezzo_di_listino
                            quantityTypeSelected+Integer.toString(quantity),//manage_stock/stock_quantitiy
                            "",//category_ids
                            formatter.formatCellValue(row.getCell(isbnIndex, Row.MissingCellPolicy.CREATE_NULL_AS_BLANK)),//parent_sku
                            "2",//position
                            "condizione",//Attributo 1 nome
                            "Usato",//Attributo 1 valuta(e)
                            "",//Attributo 1 predefinito
                            "",
                            "",
                            ""
                            );
                        }
                        
                        
                    }
                    int percentage = (100 * i)/rows;
                    publish(percentage);
                }
                
                Date date = new Date();
                LocalDate localDate = date.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
                PrintWriter out = new PrintWriter(new FileOutputStream(fileDestination.getText() + localDate.getDayOfMonth()+ "_" +localDate.getMonthValue()+ "_" + localDate.getYear()+ "_" + LocalTime.now().getHour() + LocalTime.now().getMinute() + LocalTime.now().getSecond() + "_" + FilenameUtils.removeExtension(f.getName())+ "_" +"WooCommerce_CSV_Import.csv"), true);
                out.println(sb.toString());

                //System.out.println(sb.toString());
                out.close();
                wb.close();
                
                
            }catch(FileNotFoundException fex){
                JOptionPane.showMessageDialog(mainPanel, "Errore nell'accesso al file. É giá aperto in qualche altro programma?", "Errore", JOptionPane.WARNING_MESSAGE);
                errors = true;
                startButton.setEnabled(true);
            } catch (Throwable ex) {
                ex.printStackTrace();
                ex.getCause();
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(mainPanel, "Errore nella creazione del CSV", "Errore", JOptionPane.ERROR_MESSAGE);
                errors = true;
                startButton.setEnabled(true);
            }
            return null;
        }
        
        @Override
        protected void process(List<Integer> chunks) {
            //Aggiornamento della percentuale della progress bar
            int i = chunks.get(chunks.size()-1);
            JTA.setText(initialJTAText + System.lineSeparator() + "Progresso del file: " + i +"%");
        }
        
        @Override
        protected void done() {
            if(!errors){
                logArea.setText(JTA.getText() + System.lineSeparator() + "File CSV creato!");
            }else{
                logArea.setText(JTA.getText() + System.lineSeparator() + "Errore nella creazione del file CSV!");
            }
            startButton.setEnabled(true);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField categoryValue;
    private javax.swing.JTextField descriptionValue;
    private javax.swing.JComboBox<String> dropdownImmagini;
    private javax.swing.JButton fileChooserButton;
    private javax.swing.JTextField fileDestination;
    private javax.swing.JButton fileDestinationButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea logArea;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JComboBox<String> quantityTypeCombobox;
    private javax.swing.JTextField salePercentage;
    private javax.swing.JTextField selectedFile;
    private javax.swing.JButton startButton;
    private javax.swing.JComboBox<String> variazioneCombobox;
    private javax.swing.JComboBox<String> worksheetTypeCombobox;
    // End of variables declaration//GEN-END:variables
}
